name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Lint with flake8
      run: |
        pip3 install flake8
        flake8 app/ tests/ models/

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/

    - name: Build Docker Image
      run: |
        docker build -t ml-e2e .

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag Docker Image
      run: |
        ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        docker tag ml-e2e:latest $ECR_REGISTRY/ml-e2e:latest

    - name: Push Docker Image to ECR
      env: |
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        docker push $ECR_REGISTRY/ml-e2e:latest

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        remote-user: ec2-user
        server-ip: ${{ secrets.EC2_PUBLIC_IP }}
        remote-path: /home/ec2-user/ml-e2e
        script: |
          docker pull ${{ secrets.ECR_REGISTRY }}/ml-e2e:latest
          docker stop ml-e2e || true
          docker rm ml-e2e || true
          docker run -d -p 80:5000 --name ml-e2e ${{ secrets.ECR_REGISTRY }}/ml-e2e:latest
